-- AlterTable
ALTER TABLE "exams" ADD COLUMN     "createAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "questionCloseQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "questionOpenQuantity" INTEGER NOT NULL DEFAULT 0;
